### ISSUE TITLE
[Bug]: 'EULA=TRUE' for docker compose v1

### ISSUE THREAD

**Issue by Krondes303** [LiteLDev/levilamina-docker-server#13]
### Describe the bug

通过docker-compose.yml构建容器时，未使用’version‘语句给定docker-compose版本，默认以V1运行导致环境变量参数Env 'EULA=TRUE' 不区分大小写 

### To Reproduce

在 wine/compose.yaml 和 windows/compose.yaml 的Docker Compose 文件运行 docker compose up -d

### Expected behavior

You must accept the Minecraft EULA to run the server
Set the environment variable EULA to TRUE to accept it

### Platform

docker v25.0.4

### Version

v0.7.0

**Comment by Krondes303** [comment]
自行修改
```
version: '3.3'

services:
  levilamina-server:
    image: ghcr.io/liteldev/levilamina-server:latest-wine
    environment:
      - EULA=TRUE
    ports:
      - "19132:19132/udp"
    volumes:
      - levilamina-server-data:/data
    stdin_open: true
    tty: true

volumes:
  levilamina-server-data:
```
重建容器
```
docker-compose pull
docker-compose up -d
```
